# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170929_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='exceeds_day_calories',
            field=models.BooleanField(default=False),
        ),
    ]
