export const ACTION_GET_RECORDS = 'actionGetRecords'
export const ACTION_GET_RECORD = 'actionGetRecord'
export const ACTION_ADD_RECORD = 'actionAddRecord'
export const ACTION_UPDATE_RECORD = 'actionUpdateRecord'
export const ACTION_DELETE_RECORD = 'actionDeleteRecord'
export const ACTION_APPLY_RECORDS_FILTERS = 'actionApplyRecordsFilters'
export const CLEAR_RECORDS = 'clearRecords'
export const SET_RECORDS = 'setRecords'
export const SET_RECORDS_PAGE = 'setRecordsPage'
export const SET_RECORDS_TOTAL = 'setRecordsTotal'
export const SET_RECORD = 'setRecord'
export const SET_RECORD_FILTERS = 'setRecordFilters'

export const ACTION_GET_USERS = 'actionGetUsers'
export const ACTION_GET_USER = 'actionGetUser'
export const ACTION_ADD_USER = 'actionAddUser'
export const ACTION_UPDATE_USER = 'actionUpdateUser'
export const ACTION_DELETE_USER = 'actionDeleteUser'
export const CLEAR_USERS = 'clearUsers'
export const SET_USERS = 'setUsers'
export const SET_USERS_PAGE = 'setUsersPage'
export const SET_USERS_TOTAL = 'setUsersTotal'
export const SET_USER = 'setUser'

export const ACTION_GET_USER_CONFIG = 'actionGetUserConfig'
export const ACTION_UPDATE_USER_CONFIG = 'actionUpdateUserConfig'
export const SET_USER_CONFIG = 'setUserConfig'
